// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1CZKSmxAPEDTi1KiAY5bZLKPvje-jl0c',
    appId: '1:856339034594:web:8fcd6b4ec33af1299089bb',
    messagingSenderId: '856339034594',
    projectId: 'smartrev-4291b',
    authDomain: 'smartrev-4291b.firebaseapp.com',
    storageBucket: 'smartrev-4291b.firebasestorage.app',
    measurementId: 'G-GZ71CS4T98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRUVO_R6tba7kyg60bHmV4AQ6bIyin7hc',
    appId: '1:856339034594:android:5e9489fc037596699089bb',
    messagingSenderId: '856339034594',
    projectId: 'smartrev-4291b',
    storageBucket: 'smartrev-4291b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBilzHlPI2J-lNzQJgjImFNub78lQ2_NZo',
    appId: '1:856339034594:ios:8e3f84b987bb0eb99089bb',
    messagingSenderId: '856339034594',
    projectId: 'smartrev-4291b',
    storageBucket: 'smartrev-4291b.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBilzHlPI2J-lNzQJgjImFNub78lQ2_NZo',
    appId: '1:856339034594:ios:8e3f84b987bb0eb99089bb',
    messagingSenderId: '856339034594',
    projectId: 'smartrev-4291b',
    storageBucket: 'smartrev-4291b.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1CZKSmxAPEDTi1KiAY5bZLKPvje-jl0c',
    appId: '1:856339034594:web:96b2e1709f9737ae9089bb',
    messagingSenderId: '856339034594',
    projectId: 'smartrev-4291b',
    authDomain: 'smartrev-4291b.firebaseapp.com',
    storageBucket: 'smartrev-4291b.firebasestorage.app',
    measurementId: 'G-LRB5BTCC9R',
  );
}
